export const THEME_MODE_KEY = "theme_mode"
export const SERVER_URL_KEY = "server_url"
export const CSRF_TOKEN_KEY = "csrf_token"
export const ACCESS_TOKEN_KEY = "access_token"
export const ACCESS_TOKEN_METADATA_KEY = "access_token_metadata"
export const USER_EMAIL_KEY = "user_email"
export const THEME_NAME_KEY = "theme_name"
export const USER_NAME_KEY = "username"
