name: Web Front-end Tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - review_requested
    branches:
      - master
    paths:
      - 'src/**'

jobs:
  web_front-end_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x, 26.x]
    steps:
    - uses: actions/checkout@v4
    - name: Testing on Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache modules
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}_${{ matrix.node-version }}_${{ hashFiles('package.lock') }}
        restore-keys: |
          ${{ runner.os }}_${{ matrix.node-version }}_${{ hashFiles('package.lock') }}
    - run: npm install
    - run: npm run test:unit
